### ISSUE TITLE
Broken Deployments

### ISSUE THREAD

**Issue by pi0** [unjs/nitro-deploys#41]
- [ ] Azure functions (not responding) https://nitro-deployment.azurewebsites.net/
- [ ] Netlify edge (not found) https://nitro-deployment-edge.netlify.app/
- [ ] Github pages (styles broken) https://unjs.github.io/nitro-deploys/
- [x] Firebase hosting (old deployment) https://nitro-deployment.web.app/
- [x] Digital ocean (old deployment) https://nitro-deployment-w5dzm.ondigitalocean.app/
- [x] Heroku (application error) https://nitro-deployment.herokuapp.com/
- [x] Render.com (not responding) https://nitro-deployment.onrender.com/
- [x] Stormkit (404) https://chilllunar-mnn7rl.stormkit.dev/

**Comment by ashutosh887** [comment]
I would like to work on this if open? @pi0

**Comment by pi0** [comment]
Broken deployments are now in https://github.com/unjs/nitro-deploys/blob/main/deployments.ts

@ashutosh887 that would be amazing feel free to contribute ❤️

**Comment by ashutosh887** [comment]
Closed @pi0 😄

**Comment by pi0** [comment]
Yeah. Keeping track of deployments (and broken ones in https://github.com/unjs/nitro-deploys/blob/main/deployments.ts). Feel free to open new issue for any of them you want to work on fix.
